In [1]:
import scipy as sp
import numpy as np
import cufflinks as cf
import pandas as pd

from flycast import brick_spring_simple 

# Off line settings for Cufflinks
cf.set_config_file(offline=True)
pd.options.display.html.table_schema = True

In [ ]:
k = 1.0
m = 0.01
d0 = 0
start_cond = [0, 0] # [x(t0), v(t0)]
ts = [1.0, 0.3, 0.45] # [sim_tmax, t_break, t_stop]
vct = [0, 18, 0]      # [v_car(t0), v_car_max, v_car_end]
res = brick_spring_simple(k, m, d0, start_cond, ts, vct)

In [ ]:
res.columns

In [ ]:
res.loc[:, ['sp_ext',]].iplot()

In [ ]:
res.loc[:, ['sp_e', 'brick_e']].iplot()

In [ ]:
?np.allclose

In [ ]:
from plotly.subplots import make_subplots

In [ ]:
fig = make_subplots(2,1)

In [ ]:
# stuff = res.loc[:, ['force',]].figure(yTitle=r"$Force\ \ [N]$")
# # staff = res.loc[:,['car_p',]].iplot(yTitle=r"$Power\ \ [W]$", xTitle=r"$Time\ \ [s]$", asFigure=True)
# fig.add_trace(stuff)
# # fig.add_trace(staff)

# # force_fig = cf.Figure()
# # force_fig.set_subplots(rows=2, cols=1, shared_xaxes=True)
# # force_fig.add_trace(stuff)
# # force_fig.add_trace(staff)

In [ ]:
# ?cf.Figure.get_subplot
#force_fig.set_subplots(rows=2, cols=1, shared_xaxes=True)
# force_fig.add_trace(res.loc[:, ['force',]].figure(yTitle=r"$Force\ \ [N]$"))
# force_fig.add_trace(res.loc[:,['car_p',]].figure(yTitle=r"$Power\ \ [W]$",
#                                                  xTitle=r"$Time\ \ [s]$"))

In [ ]:
import streamlit as st

In [ ]:
?st.altair_chart

In [ ]:
pd.options.plotting.backend = "plotly"

In [ ]:
res.plot(xtitle=r"$Time\ \ [s]$")

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(res.iloc[:, [0,2,3]], labels=dict(index=r"$time\ [s]$", value="Position"))

In [ ]:
fig.axis

In [ ]:
import plotly.graph_objects as go

In [ ]:
stuff = go.Scatter(x=[1, 2, 3], y=[4, 5, 6])

In [ ]:
stuff.

In [ ]:
type(fig)

In [ ]:
stuff = go.Scatter(y=res, x=res.index)

In [ ]:
?go.Scatter

In [ ]:
stuff = st.empty()

In [ ]:
?stuff.image

In [2]:
from skimage.draw import line, line_aa, line_nd

In [4]:
line_aa(0,0, 10, 10)

(array([ 0,  1,  0,  1,  2,  1,  2,  3,  2,  3,  4,  3,  4,  5,  4,  5,  6,
         5,  6,  7,  6,  7,  8,  7,  8,  9,  8,  9, 10,  9, 10]),
 array([ 0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,
         6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10]),
 array([1.        , 0.29289322, 0.29289322, 1.        , 0.29289322,
        0.29289322, 1.        , 0.29289322, 0.29289322, 1.        ,
        0.29289322, 0.29289322, 1.        , 0.29289322, 0.29289322,
        1.        , 0.29289322, 0.29289322, 1.        , 0.29289322,
        0.29289322, 1.        , 0.29289322, 0.29289322, 1.        ,
        0.29289322, 0.29289322, 1.        , 0.29289322, 0.29289322,
        1.        ]))

In [5]:
?np.ones

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.